name: Terraform CI

on:
  push:
    branches:
      - features/sujeet

  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - preprod
          - prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./environment/${{ matrix.environment }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./environment/${{ matrix.environment }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./environment/${{ matrix.environment }}